name: 'build-test'
on: # rebuild any PRs and main branch changes
  push:
    tags:
      - "v*"

jobs:
  release: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set tag name output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Test Project ${{ steps.vars.outputs.tag }}
          files: |
            LICENSE
